application:
  autoupdate: true
  workingdir: ./test-dir
  cachedir: /home/billy/.cache/server-tool
minecraft:
  quiet: false
  gui: false
  noeula: false
  memory: 6144
git:
  enable: true
  uselockfile: true
