application:
  forcetui: false
  workingdir: ./test-dir
  cachedir: /home/billy/.cache/server-tool
minecraft:
  quiet: false
  nogui: true
  noeula: false
java:
  executableoverride: ""
  memory:
    amount: 6
    gigabytes: true
  flags:
    extraflags: []
    overridedefault: false
git:
  disable: false
  disablegithubintegration: false
  uselockfile: true
  overrides:
    enable: false
    customprecommands: []
    custompostcommands: []
